insert into movies (id, name, year, genre, rating) values (1, 'Alvarez Kelly', 1991, 'Western', 6.1);
insert into movies (id, name, year, genre, rating) values (2, 'Point and Shoot', 2005, 'Documentary', 3.4);
insert into movies (id, name, year, genre, rating) values (3, 'Adulthood', 2012, 'Drama', 7.7);
insert into movies (id, name, year, genre, rating) values (4, 'Godzilla vs. Gigan (Chikyû kogeki meirei: Gojira tai Gaigan)', 2002, 'Action|Adventure|Horror', 2.5);
insert into movies (id, name, year, genre, rating) values (5, 'Mad About Mambo', 1993, 'Comedy|Romance', 7.2);
insert into movies (id, name, year, genre, rating) values (6, 'Stacy''s Knights', 1990, 'Drama', 5.8);
insert into movies (id, name, year, genre, rating) values (7, 'Barricade', 1996, 'Horror|Thriller', 8.0);
insert into movies (id, name, year, genre, rating) values (8, 'Salon Kitty', 2006, 'Drama', 6.7);
insert into movies (id, name, year, genre, rating) values (9, 'Knockout', 2006, 'Action|Drama', 4.8);
insert into movies (id, name, year, genre, rating) values (10, 'Darling', 1992, 'Drama', 7.1);
insert into movies (id, name, year, genre, rating) values (11, 'Ninja Assassin', 2005, 'Action|Crime|Drama|Thriller', 7.7);
insert into movies (id, name, year, genre, rating) values (12, 'Dealer', 1990, 'Drama', 2.4);
insert into movies (id, name, year, genre, rating) values (13, 'Palo Alto', 1990, 'Drama', 7.8);
insert into movies (id, name, year, genre, rating) values (14, 'King of Escape, The (Le roi de l''évasion)', 2008, 'Adventure|Comedy', 9.6);
insert into movies (id, name, year, genre, rating) values (15, 'Tender Is the Night', 2011, 'Drama', 6.4);
insert into movies (id, name, year, genre, rating) values (16, 'Get Crazy', 1994, 'Comedy', 9.2);
insert into movies (id, name, year, genre, rating) values (17, 'Princess Diaries, The', 2010, 'Children|Comedy|Romance', 5.0);
insert into movies (id, name, year, genre, rating) values (18, 'Blue Vinyl', 1999, 'Documentary', 3.4);
insert into movies (id, name, year, genre, rating) values (19, 'Everything About Mustafa (Mustafa hakkinda hersey)', 2005, 'Drama|Thriller', 7.2);
insert into movies (id, name, year, genre, rating) values (20, 'Prime Suspect 7: The Final Act', 1993, 'Crime|Drama|Mystery|Thriller', 5.4);
insert into movies (id, name, year, genre, rating) values (21, 'Only You', 1966, 'Comedy|Romance', 8.2);
insert into movies (id, name, year, genre, rating) values (22, 'Windows', 1993, 'Drama', 3.6);
insert into movies (id, name, year, genre, rating) values (23, 'Jekyll & Hyde... Together Again', 2008, 'Comedy|Sci-Fi', 3.2);
insert into movies (id, name, year, genre, rating) values (24, 'It''s a Wonderful Life', 1995, 'Drama|Fantasy|Romance', 2.8);
insert into movies (id, name, year, genre, rating) values (25, 'Doc Savage: The Man of Bronze', 2005, 'Adventure', 3.6);
insert into movies (id, name, year, genre, rating) values (26, 'Doorway to Hell, The', 2003, 'Crime|Drama', 8.6);
insert into movies (id, name, year, genre, rating) values (27, 'Killjoy 3', 1985, 'Horror', 1.4);
insert into movies (id, name, year, genre, rating) values (28, 'We Are Young. We Are Strong.', 1995, 'Drama', 6.3);
insert into movies (id, name, year, genre, rating) values (29, 'Bleak Moments', 1998, 'Comedy|Drama', 5.5);
insert into movies (id, name, year, genre, rating) values (30, 'Countdown to Zero', 2009, 'Documentary', 4.8);
insert into movies (id, name, year, genre, rating) values (31, 'Syrian Bride, The', 1996, 'Drama', 8.3);
insert into movies (id, name, year, genre, rating) values (32, 'Mildred Pierce', 1991, 'Drama|Film-Noir', 2.2);
insert into movies (id, name, year, genre, rating) values (33, 'Little Shop of Horrors', 2000, 'Comedy|Horror|Musical', 9.2);
insert into movies (id, name, year, genre, rating) values (34, 'Two Much', 1993, 'Comedy|Romance', 2.5);
insert into movies (id, name, year, genre, rating) values (35, 'Princess of Mars', 2002, 'Sci-Fi|Thriller|War', 5.6);
insert into movies (id, name, year, genre, rating) values (36, 'In & Out', 1992, 'Comedy', 4.4);
insert into movies (id, name, year, genre, rating) values (37, 'Lovers & Leavers (Kuutamolla)', 2010, 'Drama|Romance', 2.2);
insert into movies (id, name, year, genre, rating) values (38, 'Big Trail, The', 2000, 'Adventure|Romance|Western', 5.1);
insert into movies (id, name, year, genre, rating) values (39, 'Trick or Treat', 1994, 'Horror', 10.0);
insert into movies (id, name, year, genre, rating) values (40, 'Humble Pie (American Fork)', 2011, 'Comedy|Drama', 6.9);
insert into movies (id, name, year, genre, rating) values (41, 'Melvin and Howard', 2009, 'Drama', 1.4);
insert into movies (id, name, year, genre, rating) values (42, 'Drive Angry', 2003, 'Action|Fantasy|Thriller', 6.9);
insert into movies (id, name, year, genre, rating) values (43, 'Lust for Gold (Duhul aurului)', 2004, 'Drama', 8.8);
insert into movies (id, name, year, genre, rating) values (44, 'House of Yes, The', 1996, 'Comedy|Drama', 8.3);
insert into movies (id, name, year, genre, rating) values (45, 'Just Anybody (Le premier venu)', 2006, 'Drama|Romance', 1.5);
insert into movies (id, name, year, genre, rating) values (46, 'Hammer of the Gods', 2000, 'Action', 4.7);
insert into movies (id, name, year, genre, rating) values (47, 'Fantastic Planet, The (Planète sauvage, La)', 2011, 'Animation|Sci-Fi', 5.6);
insert into movies (id, name, year, genre, rating) values (48, 'Fire in Castilla (Tactilvision from the Moor of the Fright)', 1996, 'Documentary', 9.2);
insert into movies (id, name, year, genre, rating) values (49, 'Confidentially Yours (Vivement dimanche!)', 2010, 'Comedy|Crime|Mystery|Thriller', 7.6);
insert into movies (id, name, year, genre, rating) values (50, 'Bullet for Joey, A', 2000, 'Crime|Drama|Film-Noir|Thriller', 2.0);
insert into movies (id, name, year, genre, rating) values (51, 'Café de Flore', 2009, 'Drama', 9.0);
insert into movies (id, name, year, genre, rating) values (52, 'Hot Fuzz', 2006, 'Action|Comedy|Crime|Mystery', 1.8);
insert into movies (id, name, year, genre, rating) values (53, 'Beautiful Kate', 2005, 'Drama|Mystery', 8.4);
insert into movies (id, name, year, genre, rating) values (54, 'How to Make Love to a Woman', 2003, 'Comedy|Romance', 2.4);
insert into movies (id, name, year, genre, rating) values (55, 'Highway ', 2010, 'Crime|Drama|Romance', 9.4);
insert into movies (id, name, year, genre, rating) values (56, 'War Made Easy: How Presidents & Pundits Keep Spinning Us to Death', 1991, 'Documentary|War', 1.9);
insert into movies (id, name, year, genre, rating) values (57, 'Melody', 1995, 'Drama|Romance', 5.5);
insert into movies (id, name, year, genre, rating) values (58, '633 Squadron', 2000, 'Drama|War', 9.0);
insert into movies (id, name, year, genre, rating) values (59, 'Norte, the End of History', 2002, 'Drama', 3.4);
insert into movies (id, name, year, genre, rating) values (60, 'Quiet, The', 2012, 'Crime|Drama|Mystery|Thriller', 3.0);
insert into movies (id, name, year, genre, rating) values (61, 'Romancing the Stone', 2005, 'Action|Adventure|Comedy|Romance', 3.5);
insert into movies (id, name, year, genre, rating) values (62, 'Eyjafjallajökull', 1990, 'Comedy', 2.2);
insert into movies (id, name, year, genre, rating) values (63, 'Alien Nation: Dark Horizon', 2008, 'Drama|Sci-Fi', 3.4);
insert into movies (id, name, year, genre, rating) values (64, 'Priest', 1987, 'Action|Horror|Sci-Fi|Thriller', 4.7);
insert into movies (id, name, year, genre, rating) values (65, 'Sound and Fury', 2012, 'Documentary', 9.9);
insert into movies (id, name, year, genre, rating) values (66, 'A Matador''s Mistress', 1985, 'Drama|Romance', 3.1);
insert into movies (id, name, year, genre, rating) values (67, 'Henry', 1997, 'Comedy', 5.7);
insert into movies (id, name, year, genre, rating) values (68, '1000 Journals', 1996, '(no genres listed)', 4.8);
insert into movies (id, name, year, genre, rating) values (69, 'Frankenstein 90', 1996, 'Comedy|Horror|Romance', 2.2);
insert into movies (id, name, year, genre, rating) values (70, 'Carousel', 1997, 'Musical|Romance', 2.1);
insert into movies (id, name, year, genre, rating) values (71, 'Trancers II', 1995, 'Action|Sci-Fi', 5.1);
insert into movies (id, name, year, genre, rating) values (72, 'Sorority Wars', 1967, 'Comedy|Drama', 4.4);
insert into movies (id, name, year, genre, rating) values (73, 'Day, The', 1997, 'Drama|Sci-Fi|Thriller', 2.0);
insert into movies (id, name, year, genre, rating) values (74, 'French Connection II', 1997, 'Action|Crime|Drama|Thriller', 7.8);
insert into movies (id, name, year, genre, rating) values (75, 'This Could Be The Night', 2009, 'Comedy', 1.6);
insert into movies (id, name, year, genre, rating) values (76, 'The Testimony', 2011, '(no genres listed)', 5.4);
insert into movies (id, name, year, genre, rating) values (77, 'Quicksilver Highway', 1995, 'Horror|Thriller', 6.0);
insert into movies (id, name, year, genre, rating) values (78, 'Zodiac', 1997, 'Sci-Fi', 5.9);
insert into movies (id, name, year, genre, rating) values (79, 'Gravity', 1997, 'Action|Sci-Fi|IMAX', 4.9);
insert into movies (id, name, year, genre, rating) values (80, 'Teenage', 2008, 'Documentary', 9.3);
insert into movies (id, name, year, genre, rating) values (81, 'Once a Thief (Zong heng si hai)', 2011, 'Action|Comedy|Crime|Thriller', 8.0);
insert into movies (id, name, year, genre, rating) values (82, 'Playing ''In the Company of Men'' (En jouant ''Dans la compagnie des hommes'')', 1997, 'Drama', 1.3);
insert into movies (id, name, year, genre, rating) values (83, 'Great Santini, The', 1994, 'Drama', 4.2);
insert into movies (id, name, year, genre, rating) values (84, 'Out Cold', 2004, 'Comedy|Thriller', 2.7);
insert into movies (id, name, year, genre, rating) values (85, 'Toy Story 3', 2013, 'Adventure|Animation|Children|Comedy|Fantasy|IMAX', 7.3);
insert into movies (id, name, year, genre, rating) values (86, 'Generation Um...', 1996, 'Drama', 4.1);
insert into movies (id, name, year, genre, rating) values (87, 'In the Land of Women', 2011, 'Comedy|Drama|Romance', 4.1);
insert into movies (id, name, year, genre, rating) values (88, 'Werckmeister Harmonies (Werckmeister harmóniák)', 2004, 'Drama', 7.9);
insert into movies (id, name, year, genre, rating) values (89, 'Profound Desires of the Gods (Kamigami no fukaki yokubo) ', 2010, 'Drama', 4.8);
insert into movies (id, name, year, genre, rating) values (90, 'Vendetta', 1962, 'Action|Crime', 6.8);
insert into movies (id, name, year, genre, rating) values (91, '8 Women', 2009, 'Comedy|Crime|Musical|Mystery', 5.6);
insert into movies (id, name, year, genre, rating) values (92, 'Wayward Bus, The', 2012, 'Drama', 3.8);
insert into movies (id, name, year, genre, rating) values (93, 'Beyond The Hills', 1993, 'Drama', 7.6);
insert into movies (id, name, year, genre, rating) values (94, 'Non-Stop', 2011, 'Action|Comedy|Crime', 3.8);
insert into movies (id, name, year, genre, rating) values (95, 'Pulp Fiction', 1997, 'Comedy|Crime|Drama|Thriller', 7.2);
insert into movies (id, name, year, genre, rating) values (96, 'Tristram Shandy: A Cock and Bull Story', 1990, 'Comedy|Drama', 5.3);
insert into movies (id, name, year, genre, rating) values (97, 'Back Door to Hell', 2006, 'Drama|War', 2.9);
insert into movies (id, name, year, genre, rating) values (98, 'Lascars', 1987, 'Animation|Comedy', 10.0);
insert into movies (id, name, year, genre, rating) values (99, 'Pervert''s Guide to Ideology, The', 1995, 'Documentary', 8.1);
insert into movies (id, name, year, genre, rating) values (100, 'Underclassman', 1988, 'Action|Comedy|Thriller', 9.6);
